# Generated by Django 4.0.3 on 2022-03-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT_ROLE', 'Студент'), ('TEACHER_ROLE', 'Учитель')], default='STUDENT_ROLE', max_length=30, verbose_name='Роль'),
        ),
    ]
