# Generated by Django 4.0.3 on 2022-03-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rating_rating_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Студент'), ('TEACHER', 'Учитель')], default='STUDENT', max_length=30, verbose_name='Роль'),
        ),
    ]
