# Generated by Django 4.0.3 on 2022-03-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_defaultabstractfields_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultabstractfields',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
