# Generated by Django 4.0.3 on 2022-04-10 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(max_length=90, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сложность курса',
                'verbose_name_plural': 'Сложности курсов',
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(max_length=128, verbose_name='Название тарифа')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Цена')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(max_length=128)),
                ('difficulty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.difficulty', verbose_name='Сложность')),
                ('rate_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.rateplan')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Валидна?')),
                ('rate_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='course.rateplan', verbose_name='Тариф')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'unique_together': {('user', 'is_active')},
            },
        ),
    ]
