# Generated by Django 4.0.3 on 2022-03-30 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_avatar'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rateplan',
            options={'ordering': ['order'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='rateplan',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='defaultabstractfields_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultabstractfields'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rateplan',
            name='defaultabstractfields_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultabstractfields'),
            preserve_default=False,
        ),
    ]
