# Generated by Django 4.0.3 on 2022-04-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='rate_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.rateplan', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
