# Generated by Django 4.0.3 on 2022-04-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image_alter_course_rate_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, help_text='От 1 до 3', max_length=2, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.DeleteModel(
            name='Difficulty',
        ),
    ]
