# Generated by Django 4.0.3 on 2022-03-25 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Название')),
                ('status', models.CharField(choices=[('UNDONE', 'Не закончил'), ('DONE', 'Закончил')], default='UNDONE', max_length=20, verbose_name='Статус')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Вопрос')),
                ('type', models.CharField(choices=[('TEST', 'Тестовое'), ('TEXT', 'Текстовое')], default='TEST', max_length=16, verbose_name='Тип задания')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
        migrations.CreateModel(
            name='TaskVariantThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.task')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.variant')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='variants',
            field=models.ManyToManyField(through='lessons.TaskVariantThroughModel', to='lessons.variant'),
        ),
        migrations.CreateModel(
            name='LessonAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/files/', verbose_name='Файл')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Дополнение к тесту',
                'verbose_name_plural': 'Дополнения к тесту',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNDONE', 'Не закончил'), ('DONE', 'Закончил')], default='UNDONE', max_length=120, verbose_name='Статус')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lessons.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'STUDENT_ROLE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Назначение задания',
                'verbose_name_plural': 'Назначения заданий',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('points', models.FloatField(default=0, verbose_name='Количество баллов')),
                ('answers', models.ManyToManyField(to='lessons.variant')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lessons.task', verbose_name='Задача')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'STUDENT_ROLE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ответ на задание',
                'verbose_name_plural': 'Ответы на задание',
            },
        ),
    ]
