# Generated by Django 4.0.3 on 2022-05-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_rename_background_lesson_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'Сданный тест', 'verbose_name_plural': 'Сданные тесты'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(blank=True, choices=[('UNDONE', 'Не закончил'), ('DONE', 'Закончил')], default='UNDONE', max_length=20, verbose_name='Статус'),
        ),
    ]
