# Generated by Django 4.0.3 on 2022-06-06 18:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0006_alter_submission_options_lesson_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submission',
            new_name='Assignment',
        ),
    ]
